export const typography = {
  'typo-title-xxl': {
    fontFamily: 'var(--fractal-semantic-typography-title-xxl-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-xxl-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-xxl-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-xxl-font-size)',
  },
  'typo-title-xxl-bold': {
    fontFamily: 'var(--fractal-semantic-typography-title-xxl-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-xxl-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-xxl-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-xxl-bold-font-size)',
  },
  'typo-title-xxl-medium': {
    fontFamily: 'var(--fractal-semantic-typography-title-xxl-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-xxl-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-xxl-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-xxl-medium-font-size)',
  },
  'typo-title-xl-bold': {
    fontFamily: 'var(--fractal-semantic-typography-title-xl-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-xl-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-xl-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-xl-bold-font-size)',
  },
  'typo-title-xl-medium': {
    fontFamily: 'var(--fractal-semantic-typography-title-xl-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-xl-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-xl-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-xl-medium-font-size)',
  },
  'typo-title-l-bold': {
    fontFamily: 'var(--fractal-semantic-typography-title-l-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-l-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-l-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-l-bold-font-size)',
  },
  'typo-title-l-medium': {
    fontFamily: 'var(--fractal-semantic-typography-title-l-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-l-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-l-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-l-medium-font-size)',
  },
  'typo-title-m-bold': {
    fontFamily: 'var(--fractal-semantic-typography-title-m-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-m-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-m-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-m-bold-font-size)',
  },
  'typo-title-m-medium': {
    fontFamily: 'var(--fractal-semantic-typography-title-m-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-m-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-m-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-m-medium-font-size)',
  },
  'typo-title-s-bold': {
    fontFamily: 'var(--fractal-semantic-typography-title-s-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-s-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-s-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-s-bold-font-size)',
  },
  'typo-title-s-medium': {
    fontFamily: 'var(--fractal-semantic-typography-title-s-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-s-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-s-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-s-medium-font-size)',
  },
  'typo-title-xs-bold': {
    fontFamily: 'var(--fractal-semantic-typography-title-xs-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-xs-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-xs-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-xs-bold-font-size)',
  },
  'typo-title-xs-medium': {
    fontFamily: 'var(--fractal-semantic-typography-title-xs-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-title-xs-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-title-xs-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-title-xs-medium-font-size)',
  },
  'typo-text-xxl': {
    fontFamily: 'var(--fractal-semantic-typography-text-xxl-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xxl-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xxl-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xxl-font-size)',
  },
  'typo-text-xxl-bold': {
    fontFamily: 'var(--fractal-semantic-typography-text-xxl-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xxl-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xxl-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xxl-bold-font-size)',
  },
  'typo-text-xxl-medium': {
    fontFamily: 'var(--fractal-semantic-typography-text-xxl-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xxl-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xxl-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xxl-medium-font-size)',
  },
  'typo-text-xl-bold': {
    fontFamily: 'var(--fractal-semantic-typography-text-xl-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xl-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xl-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xl-bold-font-size)',
  },
  'typo-text-xl-medium': {
    fontFamily: 'var(--fractal-semantic-typography-text-xl-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xl-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xl-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xl-medium-font-size)',
  },
  'typo-text-xl': {
    fontFamily: 'var(--fractal-semantic-typography-text-xl-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xl-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xl-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xl-font-size)',
  },
  'typo-text-l-bold': {
    fontFamily: 'var(--fractal-semantic-typography-text-l-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-l-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-l-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-l-bold-font-size)',
  },
  'typo-text-l-medium': {
    fontFamily: 'var(--fractal-semantic-typography-text-l-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-l-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-l-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-l-medium-font-size)',
  },
  'typo-text-l': {
    fontFamily: 'var(--fractal-semantic-typography-text-l-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-l-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-l-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-l-font-size)',
  },
  'typo-text-m-bold': {
    fontFamily: 'var(--fractal-semantic-typography-text-m-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-m-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-m-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-m-bold-font-size)',
  },
  'typo-text-m-medium': {
    fontFamily: 'var(--fractal-semantic-typography-text-m-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-m-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-m-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-m-medium-font-size)',
  },
  'typo-text-m': {
    fontFamily: 'var(--fractal-semantic-typography-text-m-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-m-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-m-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-m-font-size)',
  },
  'typo-text-s': {
    fontFamily: 'var(--fractal-semantic-typography-text-s-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-s-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-s-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-s-font-size)',
  },
  'typo-text-s-bold': {
    fontFamily: 'var(--fractal-semantic-typography-text-s-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-s-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-s-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-s-bold-font-size)',
  },
  'typo-text-s-medium': {
    fontFamily: 'var(--fractal-semantic-typography-text-s-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-s-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-s-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-s-medium-font-size)',
  },
  'typo-text-xs': {
    fontFamily: 'var(--fractal-semantic-typography-text-xs-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xs-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xs-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xs-font-size)',
  },

  'typo-text-xs-medium': {
    fontFamily: 'var(--fractal-semantic-typography-text-xs-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xs-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xs-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xs-medium-font-size)',
  },

  'typo-text-xs-bold': {
    fontFamily: 'var(--fractal-semantic-typography-text-xs-bold-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xs-bold-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xs-bold-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xs-bold-font-size)',
  },

  'typo-text-xxs': {
    fontFamily: 'var(--fractal-semantic-typography-text-xxs-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xxs-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xxs-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xxs-font-size)',
  },

  'typo-text-xxs-medium': {
    fontFamily: 'var(--fractal-semantic-typography-text-xxs-medium-font-family)',
    fontWeight: 'var(--fractal-semantic-typography-text-xxs-medium-font-weight)',
    lineHeight: 'var(--fractal-semantic-typography-text-xxs-medium-line-height)',
    fontSize: 'var(--fractal-semantic-typography-text-xxs-medium-font-size)',
  },
} as const
